### ISSUE TITLE
Add CORS by default in apache.conf

### ISSUE THREAD

**Issue by PierreNansot** [kartoza/docker-qgis-server#12]
Hi, 

Thank you very much for your work.

Is it ok to add "Header set Access-Control-Allow-Origin "*" " by default in <location> in the apache conf ?
I can't request my WFS server from a client api like openlayers without CORS.

Thanks in advance

**Comment by timlinux** [comment]
Can you provide a patch for this and I will apply it. Thanks.

**Comment by timlinux** [comment]
OK I added it her https://github.com/kartoza/docker-qgis-server/blob/develop/2.18/runtime/etc/apache2/conf-enabled/qgis.conf

**Comment by PierreNansot** [comment]
That's was it.
Thanks a lot
