### ISSUE TITLE
Error building image

### ISSUE THREAD

**Issue by rastermanden** [kartoza/docker-qgis-server#7]
When I try to build the image i get the following error:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qgis-mapserver : Depends: qgis-providers (= 2.4.0+wheezy1) but it is not going to be installed
                  Depends: libgdal1 (>= 1.8.0) but it is not installable
                  Depends: libqgis-analysis2.4.0 but it is not going to be installed
                  Depends: libqgis-core2.4.0 but it is not going to be installed
                  Depends: libspatialindex1 but it is not installable

**Comment by timlinux** [comment]
Closing this as old. Please reopen if needed.
